config/routes.rb
TEQIPPesit::Application.routes.draw do
  resources :event_files

  resources :publications

  resources :projects

  resources :people

  resources :events

  resources :partners

  devise_for :users
  resources :dashboard
  root to:"home#index"

end

app/models/publication.rb
class Publication < ActiveRecord::Base
  attr_protected
  has_attached_file :abstract
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.order(:id).page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @publications }
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    if @publication.empty_flag.to_s.include?("t")
       @publication.empty_flag=false
       @publication.abstract=nil
       @publication.save
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/new
  # GET /publications/new.json
  def new
    @publication = Publication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @publication }
    end
  end

  # GET /publications/1/edit
  def edit
    @publication = Publication.find(params[:id])
    @publication.empty_flag=false
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(params[:publication])

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render json: @publication, status: :created, location: @publication }
      else
        format.html { render action: "new" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /publications/1
  # PUT /publications/1.json
  def update
    @publication = Publication.find(params[:id])
    respond_to do |format|
      if @publication.update_attributes(params[:publication])
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication = Publication.find(params[:id])
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(@publication) do |f| %>
  <% if @publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
      <% @publication.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <h3>Author</h3>
    <%= f.text_field :author, :required => true %>
  </div><br />
  <div class="field">
    <h3>Co-authors, If Any</h3>
    <%= f.text_area :co_authors, :placeholder => "Enter the co-authors separated by commas", :size => "40x5" %>
  </div><br />
  <div class="field">
    <h3>Where Was The Paper Published?</h3>
    <%= f.text_area :published_area, :size => "40x5" %>
  </div><br />
  <div class="field">
    <h3>When?</h3>
    <%= f.text_field :when, :placeholder => "yyyy/mm/dd" %>
  </div><br />
  <div class="field">
    <h3>Description</h3>
    <%= f.text_area :description, :required => true, :size => "40x5" %>
  </div><br />
  <div class="field">
    <h3>Abstract</h3>
    <%= f.file_field :abstract %>
    <%= f.label :delete? %>
    <%= f.check_box :empty_flag %>
  </div><br />
  <div class="actions">
    <center><%= f.submit %></center>
  </div>

<% end %>

app/views/publications/edit.html.erb
<% content_for :title do %>Edit publication by <%= @publication.author %><%end%>

<% if user_signed_in? %>
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />
     <link rel="stylesheet" href="/metro/css/metro.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/cards.css" />


    
  </head>
  <body>
   <div class = "main">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                
                <div class="nav-collapse collapse">
                    <ul class="nav" style = "float:right;">
                    
                        <li class=""><a href="/people">People</a> </li>
                        <li class=""><a href="/projects">Projects</a> </li>
                        <li class=""><a href="/events">Events</a> </li>
                        <li class=""><a href="/publications">Publications</a> </li>
                        <li class=""><a href="/partners">Partners</a> </li>
                        <% if user_signed_in? %>
                          <li>
                            <a href="/users/sign_out" class="sign_out" data-method="delete" rel="nofollow">
                              Sign Out 
                            </a>
                          </li>
                        <% end %>
                        
                    </ul>
                    <ul class="nav" style = "float:left;">
                        <li class=""><a href="/"><b>TEQIP-PESIT</b></a></li>
                    </ul>
                    
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
    <center>
<div style = "text-align:left; width:940px;">

<center>
<h1>Editing publication</h1>
</center>
<%= render 'form' %>

</div>
</center>
</div>
</body>
</html>
<% else %>
<h3>Log in as admin to edit </h3>
<% end %>

app/views/publications/index.html.erb
<% content_for :title do %>Listing all publications<%end%>



<!DOCTYPE html>
<html lang="en">
  <head>
  
    <link rel="stylesheet" href="metro/css/metro.css" type="text/css">
 <link rel="stylesheet" href="cards.css" type="text/css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />


    
  </head>
  <body>
   <div class = "main">
   <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                
                <div class="nav-collapse collapse">
                    <ul class="nav" style = "float:right;">
                    
                        <li class=""><a href="/people">People</a> </li>
                        <li class=""><a href="/projects">Projects</a> </li>
                        <li class=""><a href="/events">Events</a> </li>
                        <li class=""><a href="/publications">Publications</a> </li>
                        <li class=""><a href="/partners">Partners</a> </li>
                        <% if user_signed_in? %>
                          <li>
                            <a href="/users/sign_out" class="sign_out" data-method="delete" rel="nofollow">
                              Sign Out 
                            </a>
                          </li>
                        <% end %>
                        
                    </ul>
                    <ul class="nav" style = "float:left;">
                        <li class=""><a href="/"><b>TEQIP-PESIT</b></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<br><br><br>
   

<center><h1>Listing publications</h1></center><br>
<center><% if user_signed_in? %>
<%= link_to 'New Publication', new_publication_path %>
<% end %></center>

<% @publications.each do |publication| %>
 <a href="/publications/<%= publication.id %>">  
  <div class="card">
	<div class="card-inner">
	<center><h4>Author :&nbsp<%= publication.author %></h4></center>
    <center><h4>Description :&nbsp<%= publication.description %></h4></center>
  </div>
</div>
</a>  

   <center> <% if user_signed_in? %>
    <%= link_to 'Edit', edit_publication_path(publication) %> |
    <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %><% end %>
  </center>
<% end %>


<br />
<center><%= paginate @publications %></center>

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="assets/js/jquery.easing.1.3.js"></script>

    <script type="text/javascript" src="assets/js/jquery.contentcarousel.js"></script>
    <script type="text/javascript">
      $('#ca-container').contentcarousel();
    </script>
    <script src="assets/js/holder/holder.js"></script>
    
  </body>
</html>



app/views/publications/new.html.erb
<% content_for :title do %>New Publication<%end%>
<% if user_signed_in? %>
<!DOCTYPE html>
<html lang="en">
  <head>
 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />
     <link rel="stylesheet" href="/metro/css/metro.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/cards.css" />


    
  </head>
  <body>
   <div class = "main">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                
                <div class="nav-collapse collapse">
                    <ul class="nav" style = "float:right;">
                    
                        <li class=""><a href="/people">People</a> </li>
                        <li class=""><a href="/projects">Projects</a> </li>
                        <li class=""><a href="/events">Events</a> </li>
                        <li class=""><a href="/publications">Publications</a> </li>
                        <li class=""><a href="/partners">Partners</a> </li>
                        <% if user_signed_in? %>
                          <li>
                            <a href="/users/sign_out" class="sign_out" data-method="delete" rel="nofollow">
                              Sign Out 
                            </a>
                          </li>
                        <% end %>
                        
                    </ul>
                    <ul class="nav" style = "float:left;">
                        <li class=""><a href="/"><b>TEQIP-PESIT</b></a></li>
                    </ul>
                    
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
    <center>
<div style = "text-align:left; width:940px;">

<center>
<h1>New publication</h1>
</center>
<%= render 'form' %>

<%= link_to 'Back', publications_path %>




</div>
</center>
</div>
</body>
</html>
<% else %>
<h3>Log in as admin </h3>
<% end %>

app/views/publications/show.html.erb
<% content_for :title do %>Publication by <%= @publication.author %><%end%>
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" type="text/css" href="assets/css/style.css" />
     <link rel="stylesheet" href="/metro/css/metro.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/cards.css" />


    
  </head>
  <body>
   <div class = "main">
      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                
                <div class="nav-collapse collapse">
                    <ul class="nav" style = "float:right;">
                    
                        <li class=""><a href="/people">People</a> </li>
                        <li class=""><a href="/projects">Projects</a> </li>
                        <li class=""><a href="/events">Events</a> </li>
                        <li class=""><a href="/publications">Publications</a> </li>
                        <li class=""><a href="/partners">Partners</a> </li>
                        <% if user_signed_in? %>
                          <li>
                            <a href="/users/sign_out" class="sign_out" data-method="delete" rel="nofollow">
                              Sign Out 
                            </a>
                          </li>
                        <% end %>
                        
                    </ul>
                    <ul class="nav" style = "float:left;">
                        <li class=""><a href="/"><b>TEQIP-PESIT</b></a></li>
                    </ul>
                    
                </div>
            </div>
        </div>
    </div>
    <br><br><br>
    <center>
<div style = "text-align:left; width:940px;">


<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @publication.author %>
</p>
<% if @publication.co_authors.present? %>
<p>
  <% @sep=@publication.co_authors.split(",") %>
  <b>Co-Authors:</b>
  <% @sep.each do |s| %>
<br>
  <%= s %>
<% end %>
</p>
<% end %>

<% if @publication.published_area.present? %>
<p>
  <b>Published area:</b>
  <%= @publication.published_area %>
</p>
<% end %>

<% if @publication.when.is_a? Date %>
<p>
  <b>When:</b>
  <%= @publication.when %>
</p>
<% end %>

<p>
  <b>Description:</b>
  <%= @publication.description %>
</p>

<% if !@publication.abstract_file_name.nil? %>
<p>
  <b>Abstract:</b>
  <a href = "<%= @publication.abstract.url %>" >download file</a>


</p>
<% end %>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_publication_path(@publication) %> |
<% end %>
<%= link_to 'Back', publications_path %>




</div>
</center>
</div>
</body>
</html>